### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by abduelhamit** [batjko/key-peek#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Abdülhamit\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11)
KeyPeekView.initialize (c:\Users\Abdülhamit\.atom\packages\key-peek\lib\key-peek-view.coffee:12:9)
KeyPeekView.attach (c:\Users\Abdülhamit\.atom\packages\key-peek\lib\key-peek-view.coffee:30:9)
```

**Comment by batjko** [comment]
Thanks for reporting this. I'll take care of it.

**Comment by batjko** [comment]
Just published an update, which should fix this.
